language: android
env:
  global:
  - GIT_COMMITTER_NAME=ksoichiro
  - GIT_COMMITTER_EMAIL=soichiro.kashima@gmail.com
  - GIT_AUTHOR_NAME=ksoichiro
  - GIT_AUTHOR_EMAIL=soichiro.kashima@gmail.com
  - secure: JvSTH/5Jl7x3IwCvErTKoW6AjGr03MLwmJwiRQ8sDeEITeLS45EJCnpzvOZXIaxY98Uhl9WqYLYCkUWPkM6yqFEsKUEXKYFLkDoec3ek8GKUkiGWSsV5jCEkVBx8RqLWGbpSg7U/0Ua2doZqIYkBEJ1t5wKiANrt+q/04+jpXWs=
  matrix:
  - TEST_TARGET=android
  - TEST_TARGET=website
cache:
  directories:
  - website/node_modules
  - website/bower_components
install:
- true && ([ "$TEST_TARGET" != "website" ] || (cd website && npm install && cd ..))
- true && ([ "$TEST_TARGET" != "android" ] || android-update-sdk --components=build-tools-22.0.1 --accept-licenses='android-sdk-license-.+')
- true && ([ "$TEST_TARGET" != "android" ] || android-update-sdk --components=tools --accept-licenses='android-sdk-license-.+')
- true && ([ "$TEST_TARGET" != "android" ] || android-update-sdk --components=android-22 --accept-licenses='android-sdk-license-.+')
- true && ([ "$TEST_TARGET" != "android" ] || android-update-sdk --components=extra-android-support --accept-licenses='android-sdk-license-.+')
- true && ([ "$TEST_TARGET" != "android" ] || android-update-sdk --components=extra-android-m2repository --accept-licenses='android-sdk-license-.+')
script:
- "/bin/bash .travis-script.sh"
